// Code generated by go-swagger; DO NOT EDIT.

package health_check

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetV1HealthParams creates a new GetV1HealthParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetV1HealthParams() *GetV1HealthParams {
	return &GetV1HealthParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetV1HealthParamsWithTimeout creates a new GetV1HealthParams object
// with the ability to set a timeout on a request.
func NewGetV1HealthParamsWithTimeout(timeout time.Duration) *GetV1HealthParams {
	return &GetV1HealthParams{
		timeout: timeout,
	}
}

// NewGetV1HealthParamsWithContext creates a new GetV1HealthParams object
// with the ability to set a context for a request.
func NewGetV1HealthParamsWithContext(ctx context.Context) *GetV1HealthParams {
	return &GetV1HealthParams{
		Context: ctx,
	}
}

// NewGetV1HealthParamsWithHTTPClient creates a new GetV1HealthParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetV1HealthParamsWithHTTPClient(client *http.Client) *GetV1HealthParams {
	return &GetV1HealthParams{
		HTTPClient: client,
	}
}

/*
GetV1HealthParams contains all the parameters to send to the API endpoint

	for the get v1 health operation.

	Typically these are written to a http.Request.
*/
type GetV1HealthParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get v1 health params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1HealthParams) WithDefaults() *GetV1HealthParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get v1 health params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1HealthParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get v1 health params
func (o *GetV1HealthParams) WithTimeout(timeout time.Duration) *GetV1HealthParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get v1 health params
func (o *GetV1HealthParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get v1 health params
func (o *GetV1HealthParams) WithContext(ctx context.Context) *GetV1HealthParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get v1 health params
func (o *GetV1HealthParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get v1 health params
func (o *GetV1HealthParams) WithHTTPClient(client *http.Client) *GetV1HealthParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get v1 health params
func (o *GetV1HealthParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetV1HealthParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
