// Code generated by go-swagger; DO NOT EDIT.

package health_check

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new health check API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for health check API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	GetV1Health(params *GetV1HealthParams, opts ...ClientOption) (*GetV1HealthOK, *GetV1HealthCreated, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
GetV1Health healths check server

endpoint for check health server
*/
func (a *Client) GetV1Health(params *GetV1HealthParams, opts ...ClientOption) (*GetV1HealthOK, *GetV1HealthCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetV1HealthParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetV1Health",
		Method:             "GET",
		PathPattern:        "/v1/health",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json", "multipart/form-data"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetV1HealthReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, nil, err
	}
	switch value := result.(type) {
	case *GetV1HealthOK:
		return value, nil, nil
	case *GetV1HealthCreated:
		return nil, value, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*GetV1HealthDefault)
	return nil, nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
