# Swagger OpenAPI v2
# note: 
# please make sure naming of the components based on definition object name and follow the code style
swagger: "2.0"
info:
  description: "The \"REST API for TERASEHAT User Microservice\" refers to the Representational State Transfer (REST) Application Programming Interface (API) specifically tailored for the User Microservice within TERASEHAT. This API facilitates communication and interaction with the User Microservice, allowing external applications or services to execute operations related to user management within the TERASEHAT system. The API includes endpoints for user registration, authentication, and other user-related functionalities, following RESTful principles to ensure scalability and interoperability as a web service for the TERASEHAT platform"
  title: "REST API for TERASEHAT User Microservice"
  version: "1.1.1"
produces:
  - application/json
consumes:
  - application/json
  - multipart/form-data
schemes:
  - http
  # - https # use this for live server
host: "localhost:8080"
basePath: "/api"
securityDefinitions: {}
security: []

# paths
paths:
  # path health
  /v1/health:
    get:
      summary: "health check server"
      description: "endpoint for check health server"
      tags:
        - Health Check
      security: []
      responses:
        default:
          description: default
          schema:
            $ref: "#/definitions/basicResponse"
        200:
          description: ok
          schema:
            $ref: "#/definitions/healthCheckResponse"
        201:
          description: created
          schema:
            $ref: "#/definitions/basicResponse"
        400:
          description: bad request
          schema:
            $ref: "#/definitions/basicResponse"
        401:
          description: unauthorized
          schema:
            $ref: "#/definitions/basicResponse"
        403:
          description: forbidden
          schema:
            $ref: "#/definitions/basicResponse"
        404:
          description: not found
          schema:
            $ref: "#/definitions/basicResponse"
        405:
          description: method not allowed
          schema:
            $ref: "#/definitions/basicResponse"
        415:
          description: unsupported media type
          schema:
            $ref: "#/definitions/basicResponse"
        422:
          description: unprocessable entity
          schema:
            $ref: "#/definitions/basicResponse"
        500:
          description: internal server error
          schema:
            $ref: "#/definitions/basicResponse"
        502:
          description: bad gateway
          schema:
            $ref: "#/definitions/basicResponse"
  # End of path health

# --definitions
definitions:
  basicResponse:
    description: definition for basic response code & message when request to endpoint was successfull
    type: object
    properties:
      code:
        type: integer
        format: int32
        x-omitempty: false
      message:
        type: string
        x-omitempty: false
  healthCheckResponse:
    description: definition for health response with code & message when request to endpoint was successfull
    type: object
    properties:
      code:
        type: integer
        format: int32
        x-omitempty: false
      message:
        type: string
        x-omitempty: false
      results:
        type: object
        x-omitempty: false
        properties: 
          app_name:
            type: string
          app_version:
            type: string
          app_environment:
            type: string
          app_max_upload_mb:
            type: integer

  